name: GitHub Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: DishantShahare358

          # ===== Base sections =====
          base: header, activity, repositories, community

          # ===== Appearance =====
          theme: dark
          config_timezone: Asia/Kolkata

          # ===== Languages =====
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_details: bytes-size, percentage

          # ===== Achievements =====
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: C

          # ===== Activity =====
          plugin_activity: yes
          plugin_activity_limit: 6

          # ===== Habits =====
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
